server:
  port: 8089
  
spring:
  data:
    mongodb:
      database: Recommendation
      host: recommender-mongodb
      port: 27017
      
  rabbitmq:
    host: rabbitmq
    port: 5672
    template:
      exchange: bookmark.exchange
      routing-key: bookmark.created
