server:
  port: 8087
  
spring:
  data:
    mongodb:
      database: Tags
      host: tagging-mongodb
      port: 27017
      
  rabbitmq:
    host: rabbitmq
    port: 5672
    template:
      exchange: tagging.exchange
      routing-key: tagging.created